services:
  app:
    build: .
    ports: 
      - 6150:5000
    volumes:
      - .:/backend/flask_app
    environment:
      FLASK_APP: flask_app
      FLASK_DEBUG: 1
    command: flask run -h 0.0.0.0
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: flask
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    ports:
      - 6200:8080

volumes:
  db_data: